pipeline {
    agent any

    environment {
        DOCKER_REGISTRY_URL = "${params.harbor_url}"
        HARBOR_CREDENTAIL = "${params.harbor_credential}"
        GIT_USER_EMAIL = "${params.git_user_email}"
        GIT_CREDENTIAL = "${params.github_credential}"
    }

    tools {
        nodejs 'NodeJS-21.4.0' // Jenkins에서 구성한 Node.js 도구 이름 사용
    }

    stages {        

        stage('Install Dependencies') {
            steps {
                // npm 의존성 설치
                sh 'npm install'
            }
        }

        stage('Build Project') {
            steps {
                // 프로젝트 빌드
                sh 'npm run build'
            }
        }
        
        stage('Build Image for mannazo-front-react') {
          steps {
               script {
                  // Assuming the build output directory is 'dist'
                   sh 'ls $WORKSPACE' // Print workspace contents for debugging

                  // Copy built artifacts to a temporary directory for Docker build
                  sh "mkdir -p docker_build"
                   sh "cp -r $WORKSPACE/dist ./docker_build"  // Replace 'dist' with your actual build directory

                   docker.withRegistry("http://${DOCKER_REGISTRY_URL}", "${HARBOR_CREDENTAIL}") {
                       def customImage = docker.build("mannazo/front-react:${env.BUILD_NUMBER}", "-f CICD/Dockerfile ./docker_build")
                     customImage.push()
                 }
                }
            }
        }
        
        stage('Update Manifests for mannazo-deploy') {
            steps {
                script { 
                    // Git repository information for manifests
                    def manifestsRepoUrl = 'https://github.com/mannazo/mannazo-deploy.git'
                    def manifestsRepoBranch = 'main'
                    
                    // Checkout manifests repository
                    git credentialsId: "${HARBOR_CREDENTAIL}", url: manifestsRepoUrl, branch: manifestsRepoBranch
                    sh """
                        git pull origin main
                        sed -i 's|harbor.dorong9.com/mannazo/front-react:.*|harbor.dorong9.com/mannazo/front-react:${env.BUILD_NUMBER}|' web/mannazo-web.yaml
                        git add web/mannazo-web.yaml
                        git config user.name 'DOLONG9'
                        git config user.email "${GIT_USER_EMAIL}"
                        git commit -m 'web/mannazo-web.yaml ${currentBuild.number} image versioning'
                    """
                    withCredentials([gitUsernamePassword(credentialsId: "${GIT_CREDENTIAL}")]) {
                       sh "git remote set-url origin https://github.com/mannazo/mannazo-deploy.git" 
                       sh "git push origin main"
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'Cleaning up workspace...'
            deleteDir()
        }
    }
}
